name: Build and Release .NET Console Application

on: 
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --runtime win-${{ matrix.platform }} --output ${{ github.workspace }}/publish/win-${{ matrix.platform }} HowtoConsole.csproj

    - name: Upload artifact for release job
      uses: actions/upload-artifact@v4
      with:
        name: howtoconsole-win-${{ matrix.platform }}
        path: ${{ github.workspace }}/publish/win-${{ matrix.platform }}    

  create_release:
    needs: build_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag name
        id: tag
        shell: bash
        run: |
          BUILD_NUMBER="$(git rev-list --count HEAD)"
          SHORT_HASH="$(git rev-parse --short=7 HEAD)"
          if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            echo "name=b${BUILD_NUMBER}" >> $GITHUB_OUTPUT
          else
            SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
            echo "name=${SAFE_NAME}-b${BUILD_NUMBER}-${SHORT_HASH}" >> $GITHUB_OUTPUT
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: howtoconsole-artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: b${{ steps.tag.outputs.name }}
          name: Release b${{ steps.tag.outputs.name }}
          files: |
            ./howtoconsole-artifacts/howtoconsole-win-x64/howto.exe
            ./howtoconsole-artifacts/howtoconsole-win-arm64/howto.exe
