name: Build and Release .NET Console Application

on: 
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --runtime win-${{ matrix.platform }} --output ${{ github.workspace }}/publish/win-${{ matrix.platform }}

    - name: Upload artifact for release job
      uses: actions/upload-artifact@v2
      with:
        name: howtoconsole-win-${{ matrix.platform }}
        path: ${{ github.workspace }}/publish/win-${{ matrix.platform }}

  create_release:
    needs: build_and_publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: howtoconsole-artifacts

      - name: Upload x64 Release Asset
        id: upload-release-asset-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./howtoconsole-artifacts/howtoconsole-win-x64/howto.exe
          asset_name: howto-win-x64.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload ARM64 Release Asset
        id: upload-release-asset-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./howtoconsole-artifacts/howtoconsole-win-arm64/howto.exe
          asset_name: howto-win-arm64.exe
          asset_content_type: application/vnd.microsoft.portable-executable